require './db.rb'
require './library.rb'
require './entities/author.rb'
require './entities/book.rb'
require './entities/order.rb'
require './entities/reader.rb'
require './generator.rb'
require 'yaml'
